name: Manually release Kafka Bridge

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build maven project
        run: |
          mvn clean package -DskipTests -Dmaven.javadoc.skip=true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the Docker image
        run: |
          suffix=$(date +%s)
          docker build -t ghcr.io/datapunchorg/strimzi-kafka-bridge:0.22.0-SNAPSHOT-$suffix .
          docker push ghcr.io/datapunchorg/strimzi-kafka-bridge:0.22.0-SNAPSHOT-$suffix
